ipv6: false
geodata-loader: memconservative

mixed-port: 7890
allow-lan: true
bind-address: 0.0.0.0
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

profile:
  store-selected: true

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: redir-host
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - 8.8.8.8
  nameserver-policy:
    "geosite:cn,private":
      - 223.5.5.5
      - 119.29.29.29

tun:
  enable: false

redir-port: 7892

proxy-providers:
  mysub:
    type: http
    url: "https://YOUR_SUBSCRIBE_URL"
    interval: 3600
    path: ./providers/mysub.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

proxy-groups:
  - name: AUTO
    type: url-test
    use:
      - mysub
    filter: "(新加坡|香港|日本)"
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    lazy: true
    expected-status: 204

rules:
  - GEOSITE,cn,DIRECT
  - GEOSITE,private,DIRECT
  - GEOIP,CN,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - GEOSITE,google,AUTO
  - GEOSITE,youtube,AUTO
  - MATCH,AUTO
